language: rust
sudo: false
version:
    - nightly
os:
  - linux
env:
    global:
      - secure: g+2mPY1flmXP8foHSpPZzFxWPXmsgklatafe1W5Au3CqBLfeNLz2Vo1Hwee36BgK60SG+J3r6IiLlIHh5DdUreG+bkGM+VTBQ0VCoDcnN71ccOEWYAacKAUcjO5vs+D9Qvz0g16+POJhBRkDcxno0Op3Y/MZBK2S0/tLv+DzkS4=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose
after_script:
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
